// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc6Yhd_rWX2ZfOMEinCJcP2Of_mJz-nY4',
    appId: '1:49258867436:web:3a120c34b16581af7f53c9',
    messagingSenderId: '49258867436',
    projectId: 'realm-f1966',
    authDomain: 'realm-f1966.firebaseapp.com',
    storageBucket: 'realm-f1966.firebasestorage.app',
    measurementId: 'G-0NRZ2LBMWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF_naYBAIx-GCEiLpYMuRdXTLc2_nP2yg',
    appId: '1:49258867436:android:f72d7df95bb0c72a7f53c9',
    messagingSenderId: '49258867436',
    projectId: 'realm-f1966',
    storageBucket: 'realm-f1966.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHq_DCHT_6jUgCrsswmOeeYkuaMXkLUhE',
    appId: '1:49258867436:ios:6c232799739fbd4c7f53c9',
    messagingSenderId: '49258867436',
    projectId: 'realm-f1966',
    storageBucket: 'realm-f1966.firebasestorage.app',
    iosBundleId: 'com.realmworldapp.realm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHq_DCHT_6jUgCrsswmOeeYkuaMXkLUhE',
    appId: '1:49258867436:ios:ae17a8f08a1b75f27f53c9',
    messagingSenderId: '49258867436',
    projectId: 'realm-f1966',
    storageBucket: 'realm-f1966.firebasestorage.app',
    iosBundleId: 'com.example.stevenakoFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBc6Yhd_rWX2ZfOMEinCJcP2Of_mJz-nY4',
    appId: '1:49258867436:web:d0a360b8580206f27f53c9',
    messagingSenderId: '49258867436',
    projectId: 'realm-f1966',
    authDomain: 'realm-f1966.firebaseapp.com',
    storageBucket: 'realm-f1966.firebasestorage.app',
    measurementId: 'G-JKBGHW7SYR',
  );
}
